In [1]:
#import the pandas library and aliasing as pd
import pandas as pd
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [2]:
#
data = [1,2,3,4,5]
df = pd.DataFrame(data)
print(df)

   0
0  1
1  2
2  3
3  4
4  5


In [4]:
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
print(df)

     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13


In [5]:
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'],dtype=float)
print(df)

     Name   Age
0    Alex  10.0
1     Bob  12.0
2  Clarke  13.0


In [6]:
##
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data)
print(df)

   Age   Name
0   28    Tom
1   34   Jack
2   29  Steve
3   42  Ricky


In [7]:
#
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
print(df)

       Age   Name
rank1   28    Tom
rank2   34   Jack
rank3   29  Steve
rank4   42  Ricky


In [8]:
#
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data)
print(df) 

   a   b     c
0  1   2   NaN
1  5  10  20.0


In [9]:
#
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data, index=['first', 'second'])
print (df)

        a   b     c
first   1   2   NaN
second  5  10  20.0


In [11]:
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]

#With two column indices, values same as dictionary keys
df1 = pd.DataFrame(data, index=['first', 'second'], columns=['a', 'b'])

#With two column indices with one index with other name
df2 = pd.DataFrame(data, index=['first', 'second'], columns=['a', 'b1'])
print(df1)
print(df2)

        a   b
first   1   2
second  5  10
        a  b1
first   1 NaN
second  5 NaN


In [12]:
#
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
      'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
print(df)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4


In [ ]:
#
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
      'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)
print (df ['one'])


###
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
      'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)

# Adding a new column to an existing DataFrame object with column label by passing new series

print ("Adding a new column by passing as Series:")
df['three']=pd.Series([10,20,30],index=['a','b','c'])
print(df)

print ("Adding a new column using the existing columns in DataFrame:")
df['four']=df['one']+df['three']

print(df)

# Using the previous DataFrame, we will delete a column
# using del function

In [18]:
import pandas as pd

d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 
     'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd']), 
     'three' : pd.Series([10,20,30], index=['a','b','c'])}

df = pd.DataFrame(d)
print ("Our dataframe is:")
print(df)

# using del function
print ("Deleting the first column using DEL function:")
del df['one']
print(df)

# using pop function
print ("Deleting another column using POP function:")
df.pop('two')
print(df)

Our dataframe is:
   one  three  two
a  1.0   10.0    1
b  2.0   20.0    2
c  3.0   30.0    3
d  NaN    NaN    4
Deleting the first column using DEL function:
   three  two
a   10.0    1
b   20.0    2
c   30.0    3
d    NaN    4
Deleting another column using POP function:
   three
a   10.0
b   20.0
c   30.0
d    NaN


In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [20]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [21]:
dates = pd.date_range('20130101', periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
print(df)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2013-01-01  0.125796 -1.440815 -0.082662 -1.748324
2013-01-02  0.302290  1.286308  0.992057 -0.619836
2013-01-03 -1.472023  2.982251  1.432865 -1.053307
2013-01-04 -1.133768  0.559427 -0.061615 -0.193379
2013-01-05 -0.308788  0.341529 -0.215337  0.266962
2013-01-06  0.377293  0.162515 -0.638599 -0.674818


In [22]:
df2 = pd.DataFrame({'A': 1.,
                    'B': pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3]*4, dtype='int32'),
                    'E': pd.Categorical(['test', 'train', 'test', 'train']),
                    'F': 'foo'})
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


In [23]:
# Viewing data
print(df2.dtypes)
print(dir(df2))

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object
['A', 'B', 'C', 'D', 'E', 'F', 'T', '_AXIS_ALIASES', '_AXIS_IALIASES', '_AXIS_LEN', '_AXIS_NAMES', '_AXIS_NUMBERS', '_AXIS_ORDERS', '_AXIS_REVERSED', '_AXIS_SLICEMAP', '__abs__', '__add__', '__and__', '__array__', '__array_wrap__', '__bool__', '__bytes__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pow__', '

In [25]:
print(df.head())

                   A         B         C         D
2013-01-01  0.125796 -1.440815 -0.082662 -1.748324
2013-01-02  0.302290  1.286308  0.992057 -0.619836
2013-01-03 -1.472023  2.982251  1.432865 -1.053307
2013-01-04 -1.133768  0.559427 -0.061615 -0.193379
2013-01-05 -0.308788  0.341529 -0.215337  0.266962


In [26]:
print(df.tail(3))

                   A         B         C         D
2013-01-04 -1.133768  0.559427 -0.061615 -0.193379
2013-01-05 -0.308788  0.341529 -0.215337  0.266962
2013-01-06  0.377293  0.162515 -0.638599 -0.674818


In [27]:
print(df.index)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [ ]:
print(df.values)

In [24]:
print(df.describe())

                   A         B         C         D
2013-01-01  0.125796 -1.440815 -0.082662 -1.748324
2013-01-02  0.302290  1.286308  0.992057 -0.619836
2013-01-03 -1.472023  2.982251  1.432865 -1.053307
2013-01-04 -1.133768  0.559427 -0.061615 -0.193379
2013-01-05 -0.308788  0.341529 -0.215337  0.266962
                   A         B         C         D
2013-01-04 -1.133768  0.559427 -0.061615 -0.193379
2013-01-05 -0.308788  0.341529 -0.215337  0.266962
2013-01-06  0.377293  0.162515 -0.638599 -0.674818
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
[[ 0.12579563 -1.44081517 -0.08266173 -1.748324  ]
 [ 0.30229018  1.28630794  0.99205745 -0.61983591]
 [-1.47202276  2.98225105  1.43286526 -1.05330683]
 [-1.13376846  0.55942719 -0.06161545 -0.19337869]
 [-0.30878823  0.34152889 -0.21533708  0.26696246]
 [ 0.37729285  0.16251533 -0.6385991  -0.67481752]]
              A     

In [ ]:
print(df.T)
print(df.sort_index(axis=1, ascending=False))
print(df.sort_values(by='B'))

# Selection
print(df['A'])

print(type(df['A']))
print(df[0:3])
print(df['20130102':'20130104'])

print(df.loc[dates[0]])
print(df.loc['20130102'])
print(df.loc['2013-01-02'])

print(df.mean())